### ISSUE TITLE
Keyerror in Plugin Management plugin

### ISSUE THREAD

**Issue by mpsparrow** [mpsparrow/applesauce#100]
Error is thrown if someone reactions to a any message with an emoji used for navigation. I believe this is when there is no initial message stored in `activeObjects`.

```Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/scripts/rewrite-applesauce/help/applesauce/plugins/plugins/plugins.py", line 419, in on_reaction_add
    if self.activeObjects[guildid].messageHandle is None:
KeyError: 568265828856889374```

**Comment by mpsparrow** [comment]
fixed in d2c11fae6ca74ffa3a08947f3eef9d9b05f113d6
